/*
 * Twilio - Lookups
 *
 * This is the public Twilio REST API.
 *
 * API version: 5.15.0
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// LookupsV1PhoneNumber struct for LookupsV1PhoneNumber
type LookupsV1PhoneNumber struct {
	AddOns map[string]interface{} `json:"add_ons,omitempty"`
	CallerName map[string]interface{} `json:"caller_name,omitempty"`
	Carrier map[string]interface{} `json:"carrier,omitempty"`
	CountryCode string `json:"country_code,omitempty"`
	NationalFormat string `json:"national_format,omitempty"`
	PhoneNumber string `json:"phone_number,omitempty"`
	Url string `json:"url,omitempty"`
}
