/*
 * Twilio - Ip_messaging
 *
 * This is the public Twilio REST API.
 *
 * API version: 5.15.0
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineObject15 struct for InlineObject15
type InlineObject15 struct {
	Attributes string `json:"Attributes,omitempty"`
	FriendlyName string `json:"FriendlyName,omitempty"`
	RoleSid string `json:"RoleSid,omitempty"`
}
