/*
 * Twilio - Insights
 *
 * This is the public Twilio REST API.
 *
 * API version: 1.10.0
 * Contact: support@twilio.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

// VideoRoomSummaryRoomStatus the model 'VideoRoomSummaryRoomStatus'
type VideoRoomSummaryRoomStatus string

// List of video_room_summary_room_status
const (
	VIDEOROOMSUMMARYROOMSTATUS_IN_PROGRESS VideoRoomSummaryRoomStatus = "in_progress"
	VIDEOROOMSUMMARYROOMSTATUS_COMPLETED   VideoRoomSummaryRoomStatus = "completed"
)
