/*
 * Twilio - Insights
 *
 * This is the public Twilio REST API.
 *
 * API version: 1.10.0
 * Contact: support@twilio.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

// VideoRoomSummaryProcessingState the model 'VideoRoomSummaryProcessingState'
type VideoRoomSummaryProcessingState string

// List of video_room_summary_processing_state
const (
	VIDEOROOMSUMMARYPROCESSINGSTATE_COMPLETE    VideoRoomSummaryProcessingState = "complete"
	VIDEOROOMSUMMARYPROCESSINGSTATE_IN_PROGRESS VideoRoomSummaryProcessingState = "in_progress"
)
