/*
 * Twilio - Taskrouter
 *
 * This is the public Twilio REST API.
 *
 * API version: 5.15.0
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TaskrouterV1WorkspaceWorkflowWorkflowRealTimeStatistics struct for TaskrouterV1WorkspaceWorkflowWorkflowRealTimeStatistics
type TaskrouterV1WorkspaceWorkflowWorkflowRealTimeStatistics struct {
	AccountSid string `json:"account_sid,omitempty"`
	LongestTaskWaitingAge int32 `json:"longest_task_waiting_age,omitempty"`
	LongestTaskWaitingSid string `json:"longest_task_waiting_sid,omitempty"`
	TasksByPriority map[string]interface{} `json:"tasks_by_priority,omitempty"`
	TasksByStatus map[string]interface{} `json:"tasks_by_status,omitempty"`
	TotalTasks int32 `json:"total_tasks,omitempty"`
	Url string `json:"url,omitempty"`
	WorkflowSid string `json:"workflow_sid,omitempty"`
	WorkspaceSid string `json:"workspace_sid,omitempty"`
}
