/*
 * Twilio - Serverless
 *
 * This is the public Twilio REST API.
 *
 * API version: 1.0.0
 * Contact: support@twilio.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"time"
)

// ServerlessV1ServiceAssetAssetVersion struct for ServerlessV1ServiceAssetAssetVersion
type ServerlessV1ServiceAssetAssetVersion struct {
	AccountSid  *string                 `json:"account_sid,omitempty"`
	AssetSid    *string                 `json:"asset_sid,omitempty"`
	DateCreated *time.Time              `json:"date_created,omitempty"`
	Path        *string                 `json:"path,omitempty"`
	ServiceSid  *string                 `json:"service_sid,omitempty"`
	Sid         *string                 `json:"sid,omitempty"`
	Url         *string                 `json:"url,omitempty"`
	Visibility  *AssetVersionVisibility `json:"visibility,omitempty"`
}
