/*
 * Twilio - Numbers
 *
 * This is the public Twilio REST API.
 *
 * API version: 1.9.1
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Status the model 'Status'
type Status string

// List of status
const (
	STATUS_DRAFT                  Status = "draft"
	STATUS_PENDING_REVIEW         Status = "pending-review"
	STATUS_REJECTED               Status = "rejected"
	STATUS_APPROVED               Status = "approved"
	STATUS_EXPIRED                Status = "expired"
	STATUS_PROVISIONALLY_APPROVED Status = "provisionally-approved"
)
