/*
 * Twilio - Api
 *
 * This is the public Twilio REST API.
 *
 * API version: 1.0.0
 * Contact: support@twilio.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

// ApiV2010AccountNewKey struct for ApiV2010AccountNewKey
type ApiV2010AccountNewKey struct {
	DateCreated  *string `json:"date_created,omitempty"`
	DateUpdated  *string `json:"date_updated,omitempty"`
	FriendlyName *string `json:"friendly_name,omitempty"`
	Secret       *string `json:"secret,omitempty"`
	Sid          *string `json:"sid,omitempty"`
}
