/*
 * Twilio - Api
 *
 * This is the public Twilio REST API.
 *
 * API version: 5.15.0
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// UpdateSipIpAccessControlListRequest struct for UpdateSipIpAccessControlListRequest
type UpdateSipIpAccessControlListRequest struct {
	// A human readable descriptive text, up to 64 characters long.
	FriendlyName string `json:"FriendlyName"`
}
