/*
 * Twilio - Ip_messaging
 *
 * This is the public Twilio REST API.
 *
 * API version: 5.15.0
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// IpMessagingV1ServiceRoleReadResponse struct for IpMessagingV1ServiceRoleReadResponse
type IpMessagingV1ServiceRoleReadResponse struct {
	Meta IpMessagingV1CredentialReadResponseMeta `json:"meta,omitempty"`
	Roles []IpMessagingV1ServiceRole `json:"roles,omitempty"`
}
