/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Insights
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package openapi

// InsightsV1MetadataResponseCubes struct for InsightsV1MetadataResponseCubes
type InsightsV1MetadataResponseCubes struct {
	Name        string                                      `json:"name"`
	Description string                                      `json:"description,omitempty"`
	Measures    []InsightsV1MetadataResponseCubesMeasures   `json:"measures"`
	Dimensions  []InsightsV1MetadataResponseCubesDimensions `json:"dimensions"`
}
