/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Insights
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package openapi

// InsightsV1Annotation struct for InsightsV1Annotation
type InsightsV1Annotation struct {
	// The unique SID identifier of the Call.
	CallSid *string `json:"call_sid,omitempty"`
	// The unique SID identifier of the Account.
	AccountSid        *string `json:"account_sid,omitempty"`
	AnsweredBy        *string `json:"answered_by,omitempty"`
	ConnectivityIssue *string `json:"connectivity_issue,omitempty"`
	// Specify if the call had any subjective quality issues. Possible values, one or more of:  no_quality_issue, low_volume, choppy_robotic, echo, dtmf, latency, owa, static_noise. Use comma separated values to indicate multiple quality issues for the same call
	QualityIssues *[]string `json:"quality_issues,omitempty"`
	// Specify if the call was a spam call. Use this to provide feedback on whether calls placed from your account were marked as spam, or if inbound calls received by your account were unwanted spam. Is of type Boolean: true, false. Use true if the call was a spam call.
	Spam *bool `json:"spam,omitempty"`
	// Specify the call score. This is of type integer. Use a range of 1-5 to indicate the call experience score, with the following mapping as a reference for rating the call [5: Excellent, 4: Good, 3 : Fair, 2 : Poor, 1: Bad].
	CallScore *int `json:"call_score,omitempty"`
	// Specify any comments pertaining to the call. This of type string with a max limit of 100 characters. Twilio does not treat this field as PII, so don’t put any PII in here.
	Comment *string `json:"comment,omitempty"`
	// Associate this call with an incident or support ticket. This is of type string with a max limit of 100 characters. Twilio does not treat this field as PII, so don’t put any PII in here.
	Incident *string `json:"incident,omitempty"`
	// The URL of this resource.
	Url *string `json:"url,omitempty"`
}
