/*
 * Twilio - Insights
 *
 * This is the public Twilio REST API.
 *
 * API version: 1.8.0
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CallType the model 'CallType'
type CallType string

// List of call_type
const (
	CARRIER CallType = "carrier"
	SIP CallType = "sip"
	TRUNKING CallType = "trunking"
	CLIENT CallType = "client"
)
