/*
 * Twilio - Preview
 *
 * This is the public Twilio REST API.
 *
 * API version: 1.10.0
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// PreviewBulkExportsExport struct for PreviewBulkExportsExport
type PreviewBulkExportsExport struct {
	Links        *map[string]interface{} `json:"Links,omitempty"`
	ResourceType *string                 `json:"ResourceType,omitempty"`
	Url          *string                 `json:"Url,omitempty"`
}
