/*
 * Twilio - Preview
 *
 * This is the public Twilio REST API.
 *
 * API version: 1.9.1
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// VerificationType the model 'VerificationType'
type VerificationType string

// List of verification_type
const (
	VERIFICATIONTYPE_CALL VerificationType = "phone-call"
	VERIFICATIONTYPE_BILL VerificationType = "phone-bill"
)
