/*
 * Twilio - Preview
 *
 * This is the public Twilio REST API.
 *
 * API version: 0.1.1
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ListModelBuildResponse struct for ListModelBuildResponse
type ListModelBuildResponse struct {
	Meta        ListDayResponseMeta                    `json:"Meta,omitempty"`
	ModelBuilds []PreviewUnderstandAssistantModelBuild `json:"ModelBuilds,omitempty"`
}
