/*
 * Twilio - Preview
 *
 * This is the public Twilio REST API.
 *
 * API version: 1.9.1
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// UpdateTaskActionsRequest struct for UpdateTaskActionsRequest
type UpdateTaskActionsRequest struct {
	// The JSON actions that instruct the Assistant how to perform this task.
	Actions map[string]interface{} `json:"Actions,omitempty"`
}
