/*
 * Twilio - Preview
 *
 * This is the public Twilio REST API.
 *
 * API version: 5.15.0
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse2007 struct for InlineResponse2007
type InlineResponse2007 struct {
	Items []PreviewHostedNumbersAuthorizationDocument `json:"items,omitempty"`
	Meta InlineResponse200Meta `json:"meta,omitempty"`
}
