/*
 * Twilio - Preview
 *
 * This is the public Twilio REST API.
 *
 * API version: 5.15.0
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineObject53 struct for InlineObject53
type InlineObject53 struct {
	FriendlyName string `json:"FriendlyName,omitempty"`
	UniqueName string `json:"UniqueName,omitempty"`
}
