/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Marketplace
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package openapi

import (
	"encoding/json"
	"net/url"
	"strings"
)

// Optional parameters for the method 'CreateBillingUsage'
type CreateBillingUsageParams struct {
	//
	CreateBillingUsageRequest *CreateBillingUsageRequest `json:"CreateBillingUsageRequest,omitempty"`
}

func (params *CreateBillingUsageParams) SetCreateBillingUsageRequest(CreateBillingUsageRequest CreateBillingUsageRequest) *CreateBillingUsageParams {
	params.CreateBillingUsageRequest = &CreateBillingUsageRequest
	return params
}

//
func (c *ApiService) CreateBillingUsage(InstalledAddOnSid string, params *CreateBillingUsageParams) (*MarketplaceV1BillingUsageResponse, error) {
	path := "/v1/InstalledAddOns/{InstalledAddOnSid}/Usage"
	path = strings.Replace(path, "{"+"InstalledAddOnSid"+"}", InstalledAddOnSid, -1)

	data := url.Values{}
	headers := map[string]interface{}{
		"Content-Type": "application/json",
	}

	body := []byte{}
	if params != nil && params.CreateBillingUsageRequest != nil {
		b, err := json.Marshal(*params.CreateBillingUsageRequest)
		if err != nil {
			return nil, err
		}
		body = b
	}

	resp, err := c.requestHandler.Post(c.baseURL+path, data, headers, body...)
	if err != nil {
		return nil, err
	}

	defer resp.Body.Close()

	ps := &MarketplaceV1BillingUsageResponse{}
	if err := json.NewDecoder(resp.Body).Decode(ps); err != nil {
		return nil, err
	}

	return ps, err
}
