/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Sample/reference Twilio API.
 * This is the reference API for the rest-proxy server.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package openapi

import (
	"encoding/json"

	"github.com/twilio/twilio-go/client"
)

// InsightsV2OutboundPhoneNumberReport struct for InsightsV2OutboundPhoneNumberReport
type InsightsV2OutboundPhoneNumberReport struct {
	// The outbound phone number handle.
	Handle string `json:"handle,omitempty"`
	// Total number of outbound calls made with the given handle during the report period.
	TotalCalls int `json:"total_calls,omitempty"`
	// The call answer score measures customers behavior to the delivered calls. The score is a value between 0 and 100, where 100 indicates that all calls were successfully answered.
	CallAnswerScore float32 `json:"call_answer_score,omitempty"`
	// Number of calls made with each device type. `voip`, `mobile`, `landline`, `unknown`
	CallsByDeviceType map[string]int `json:"calls_by_device_type,omitempty"`
	// Answer rate for each device type. `voip`, `mobile`, `landline`, `unknown`
	AnswerRateDeviceType map[string]float32                                     `json:"answer_rate_device_type,omitempty"`
	CallStatePercentage  InsightsV2OutboundPhoneNumberReportCallStatePercentage `json:"call_state_percentage,omitempty"`
	// Percentage of blocked calls by carrier per country.
	BlockedCallsByCarrier []CountyCarrierValue `json:"blocked_calls_by_carrier,omitempty"`
	// Percentage of calls with silence tags over total calls. A silent tag is indicative of a connectivity issue or muted audio.
	SilentCallsPercentage float32 `json:"silent_calls_percentage,omitempty"`
	// Percentage of completed outbound calls under 10 seconds (PSTN Short call tags); More than 15% is typically low trust measured.
	ShortDurationCallsPercentage float32 `json:"short_duration_calls_percentage,omitempty"`
	// Percentage of long duration calls ( >= 60 seconds)
	LongDurationCallsPercentage float32 `json:"long_duration_calls_percentage,omitempty"`
	// Percentage of completed outbound calls to unassigned or unallocated phone numbers.
	PotentialRobocallsPercentage float32                                                      `json:"potential_robocalls_percentage,omitempty"`
	AnsweringMachineDetection    InsightsV2OutboundPhoneNumberReportAnsweringMachineDetection `json:"answering_machine_detection,omitempty"`
}

func (response *InsightsV2OutboundPhoneNumberReport) UnmarshalJSON(bytes []byte) (err error) {
	raw := struct {
		Handle                       string                                                       `json:"handle"`
		TotalCalls                   int                                                          `json:"total_calls"`
		CallAnswerScore              interface{}                                                  `json:"call_answer_score"`
		CallsByDeviceType            map[string]int                                               `json:"calls_by_device_type"`
		AnswerRateDeviceType         map[string]float32                                           `json:"answer_rate_device_type"`
		CallStatePercentage          InsightsV2OutboundPhoneNumberReportCallStatePercentage       `json:"call_state_percentage"`
		BlockedCallsByCarrier        []CountyCarrierValue                                         `json:"blocked_calls_by_carrier"`
		SilentCallsPercentage        interface{}                                                  `json:"silent_calls_percentage"`
		ShortDurationCallsPercentage interface{}                                                  `json:"short_duration_calls_percentage"`
		LongDurationCallsPercentage  interface{}                                                  `json:"long_duration_calls_percentage"`
		PotentialRobocallsPercentage interface{}                                                  `json:"potential_robocalls_percentage"`
		AnsweringMachineDetection    InsightsV2OutboundPhoneNumberReportAnsweringMachineDetection `json:"answering_machine_detection"`
	}{}

	if err = json.Unmarshal(bytes, &raw); err != nil {
		return err
	}

	*response = InsightsV2OutboundPhoneNumberReport{
		Handle:                    raw.Handle,
		TotalCalls:                raw.TotalCalls,
		CallsByDeviceType:         raw.CallsByDeviceType,
		AnswerRateDeviceType:      raw.AnswerRateDeviceType,
		CallStatePercentage:       raw.CallStatePercentage,
		BlockedCallsByCarrier:     raw.BlockedCallsByCarrier,
		AnsweringMachineDetection: raw.AnsweringMachineDetection,
	}

	responseCallAnswerScore, err := client.UnmarshalFloat32(&raw.CallAnswerScore)
	if err != nil {
		return err
	}
	response.CallAnswerScore = *responseCallAnswerScore

	responseSilentCallsPercentage, err := client.UnmarshalFloat32(&raw.SilentCallsPercentage)
	if err != nil {
		return err
	}
	response.SilentCallsPercentage = *responseSilentCallsPercentage

	responseShortDurationCallsPercentage, err := client.UnmarshalFloat32(&raw.ShortDurationCallsPercentage)
	if err != nil {
		return err
	}
	response.ShortDurationCallsPercentage = *responseShortDurationCallsPercentage

	responseLongDurationCallsPercentage, err := client.UnmarshalFloat32(&raw.LongDurationCallsPercentage)
	if err != nil {
		return err
	}
	response.LongDurationCallsPercentage = *responseLongDurationCallsPercentage

	responsePotentialRobocallsPercentage, err := client.UnmarshalFloat32(&raw.PotentialRobocallsPercentage)
	if err != nil {
		return err
	}
	response.PotentialRobocallsPercentage = *responsePotentialRobocallsPercentage

	return
}
