/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio Memory API
 * APIs for managing memory stores, profiles, events, and conversational intelligence capabilities.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package openapi

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strings"

	"github.com/twilio/twilio-go/client"
	"github.com/twilio/twilio-go/client/metadata"
)

// Optional parameters for the method 'CreateProfilesImportV2'
type CreateProfilesImportV2Params struct {
	//
	CreateProfilesImportV2Request *CreateProfilesImportV2Request `json:"CreateProfilesImportV2Request,omitempty"`
}

func (params *CreateProfilesImportV2Params) SetCreateProfilesImportV2Request(CreateProfilesImportV2Request CreateProfilesImportV2Request) *CreateProfilesImportV2Params {
	params.CreateProfilesImportV2Request = &CreateProfilesImportV2Request
	return params
}

// Initiate a profile import by requesting a pre-signed upload URL and an associated `importId`. Upload your CSV to the returned URL (single PUT). Query the import status endpoint to track processing progress. This endpoint creates the import task and allocates resources for subsequent ingestion.
func (c *ApiService) CreateProfilesImportV2(StoreId string, params *CreateProfilesImportV2Params) (*CreateProfilesImportV1Response, error) {
	path := "/v1/Stores/{storeId}/Profiles/Imports"
	path = strings.Replace(path, "{"+"storeId"+"}", StoreId, -1)

	data := url.Values{}
	headers := map[string]interface{}{
		"Content-Type": "application/json",
	}

	body := []byte{}
	if params != nil && params.CreateProfilesImportV2Request != nil {
		b, err := json.Marshal(*params.CreateProfilesImportV2Request)
		if err != nil {
			return nil, err
		}
		body = b
	}

	resp, err := c.requestHandler.Post(c.baseURL+path, data, headers, c.apiVersion, body...)
	if err != nil {
		return nil, err
	}

	defer resp.Body.Close()

	ps := &CreateProfilesImportV1Response{}
	if err := json.NewDecoder(resp.Body).Decode(ps); err != nil {
		return nil, err
	}

	return ps, err
}

// CreateProfilesImportV2WithMetadata returns response with metadata like status code and response headers
func (c *ApiService) CreateProfilesImportV2WithMetadata(StoreId string, params *CreateProfilesImportV2Params) (*metadata.ResourceMetadata[CreateProfilesImportV1Response], error) {
	path := "/v1/Stores/{storeId}/Profiles/Imports"
	path = strings.Replace(path, "{"+"storeId"+"}", StoreId, -1)

	data := url.Values{}
	headers := map[string]interface{}{
		"Content-Type": "application/json",
	}

	body := []byte{}
	if params != nil && params.CreateProfilesImportV2Request != nil {
		b, err := json.Marshal(*params.CreateProfilesImportV2Request)
		if err != nil {
			return nil, err
		}
		body = b
	}

	resp, err := c.requestHandler.Post(c.baseURL+path, data, headers, c.apiVersion, body...)
	if err != nil {
		return nil, err
	}

	defer resp.Body.Close()

	ps := &CreateProfilesImportV1Response{}
	if err := json.NewDecoder(resp.Body).Decode(ps); err != nil {
		return nil, err
	}

	metadataWrapper := metadata.NewResourceMetadata[CreateProfilesImportV1Response](
		*ps,             // The resource object
		resp.StatusCode, // HTTP status code
		resp.Header,     // HTTP headers
	)

	return metadataWrapper, nil
}

// Retrieve the current processing status of a previously submitted bulk import task. Query this endpoint using the `importId` returned from the upload URL request until a terminal state (COMPLETED or FAILED) is reached.
func (c *ApiService) FetchProfileImportV2(StoreId string, ImportId string) (*FetchProfileImportV0Response, error) {
	path := "/v1/Stores/{storeId}/Profiles/Imports/{importId}"
	path = strings.Replace(path, "{"+"storeId"+"}", StoreId, -1)
	path = strings.Replace(path, "{"+"importId"+"}", ImportId, -1)

	data := url.Values{}
	headers := map[string]interface{}{
		"Content-Type": "application/x-www-form-urlencoded",
	}

	resp, err := c.requestHandler.Get(c.baseURL+path, data, headers, c.apiVersion)
	if err != nil {
		return nil, err
	}

	defer resp.Body.Close()

	ps := &FetchProfileImportV0Response{}
	if err := json.NewDecoder(resp.Body).Decode(ps); err != nil {
		return nil, err
	}

	return ps, err
}

// FetchProfileImportV2WithMetadata returns response with metadata like status code and response headers
func (c *ApiService) FetchProfileImportV2WithMetadata(StoreId string, ImportId string) (*metadata.ResourceMetadata[FetchProfileImportV0Response], error) {
	path := "/v1/Stores/{storeId}/Profiles/Imports/{importId}"
	path = strings.Replace(path, "{"+"storeId"+"}", StoreId, -1)
	path = strings.Replace(path, "{"+"importId"+"}", ImportId, -1)

	data := url.Values{}
	headers := map[string]interface{}{
		"Content-Type": "application/x-www-form-urlencoded",
	}

	resp, err := c.requestHandler.Get(c.baseURL+path, data, headers, c.apiVersion)
	if err != nil {
		return nil, err
	}

	defer resp.Body.Close()

	ps := &FetchProfileImportV0Response{}
	if err := json.NewDecoder(resp.Body).Decode(ps); err != nil {
		return nil, err
	}

	metadataWrapper := metadata.NewResourceMetadata[FetchProfileImportV0Response](
		*ps,             // The resource object
		resp.StatusCode, // HTTP status code
		resp.Header,     // HTTP headers
	)

	return metadataWrapper, nil
}

// Optional parameters for the method 'ListProfileImportsV2'
type ListProfileImportsV2Params struct {
	// Max number of records to return.
	Limit *int `json:"limit,omitempty"`
	// Max number of records to return in a page
	PageSize *int `json:"PageSize,omitempty"`
}

func (params *ListProfileImportsV2Params) SetLimit(Limit int) *ListProfileImportsV2Params {
	params.Limit = &Limit
	return params
}
func (params *ListProfileImportsV2Params) SetPageSize(PageSize int) *ListProfileImportsV2Params {
	params.PageSize = &PageSize
	return params
}

// Retrieve a single page of ProfileImportsV2 records from the API. Request is executed immediately.
func (c *ApiService) PageProfileImportsV2(StoreId string, params *ListProfileImportsV2Params, pageToken string) (*ListProfileImportsV0Response, error) {
	path := "/v1/Stores/{storeId}/Profiles/Imports"

	path = strings.Replace(path, "{"+"storeId"+"}", StoreId, -1)

	data := url.Values{}
	headers := map[string]interface{}{
		"Content-Type": "application/x-www-form-urlencoded",
	}

	if params != nil && params.PageSize != nil {
		data.Set("PageSize", fmt.Sprint(*params.PageSize))
	}

	if pageToken != "" {
		data.Set("PageToken", pageToken)
	}

	resp, err := c.requestHandler.Get(c.baseURL+path, data, headers, c.apiVersion)
	if err != nil {
		return nil, err
	}

	defer resp.Body.Close()

	ps := &ListProfileImportsV0Response{}
	if err := json.NewDecoder(resp.Body).Decode(ps); err != nil {
		return nil, err
	}

	return ps, err
}

// PageProfileImportsV2WithMetadata returns response with metadata like status code and response headers
func (c *ApiService) PageProfileImportsV2WithMetadata(StoreId string, params *ListProfileImportsV2Params, pageToken string) (*metadata.ResourceMetadata[ListProfileImportsV0Response], error) {
	path := "/v1/Stores/{storeId}/Profiles/Imports"

	path = strings.Replace(path, "{"+"storeId"+"}", StoreId, -1)

	data := url.Values{}
	headers := map[string]interface{}{
		"Content-Type": "application/x-www-form-urlencoded",
	}

	if params != nil && params.PageSize != nil {
		data.Set("PageSize", fmt.Sprint(*params.PageSize))
	}

	if pageToken != "" {
		data.Set("PageToken", pageToken)
	}

	resp, err := c.requestHandler.Get(c.baseURL+path, data, headers, c.apiVersion)
	if err != nil {
		return nil, err
	}

	defer resp.Body.Close()

	ps := &ListProfileImportsV0Response{}
	if err := json.NewDecoder(resp.Body).Decode(ps); err != nil {
		return nil, err
	}

	metadataWrapper := metadata.NewResourceMetadata[ListProfileImportsV0Response](
		*ps,             // The page object
		resp.StatusCode, // HTTP status code
		resp.Header,     // HTTP headers
	)

	return metadataWrapper, nil
}

// Lists ProfileImportsV2 records from the API as a list. Unlike stream, this operation is eager and loads 'limit' records into memory before returning.
func (c *ApiService) ListProfileImportsV2(StoreId string, params *ListProfileImportsV2Params) ([]string, error) {
	response, errors := c.StreamProfileImportsV2(StoreId, params)

	records := make([]string, 0)
	for record := range response {
		records = append(records, record)
	}

	if err := <-errors; err != nil {
		return nil, err
	}

	return records, nil
}

// ListProfileImportsV2WithMetadata returns response with metadata like status code and response headers
func (c *ApiService) ListProfileImportsV2WithMetadata(StoreId string, params *ListProfileImportsV2Params) (*metadata.ResourceMetadata[[]string], error) {
	response, errors := c.StreamProfileImportsV2WithMetadata(StoreId, params)
	resource := response.GetResource()

	records := make([]string, 0)
	for record := range resource {
		records = append(records, record)
	}

	if err := <-errors; err != nil {
		return nil, err
	}

	metadataWrapper := metadata.NewResourceMetadata[[]string](
		records,
		response.GetStatusCode(), // HTTP status code
		response.GetHeaders(),    // HTTP headers
	)

	return metadataWrapper, nil
}

// Streams ProfileImportsV2 records from the API as a channel stream. This operation lazily loads records as efficiently as possible until the limit is reached.
func (c *ApiService) StreamProfileImportsV2(StoreId string, params *ListProfileImportsV2Params) (chan string, chan error) {
	if params == nil {
		params = &ListProfileImportsV2Params{}
	}
	params.SetPageSize(client.ReadLimits(params.PageSize, params.Limit))

	recordChannel := make(chan string, 1)
	errorChannel := make(chan error, 1)

	response, err := c.PageProfileImportsV2(StoreId, params, "")
	if err != nil {
		errorChannel <- err
		close(recordChannel)
		close(errorChannel)
	} else {
		go c.streamProfileImportsV2(response, params, recordChannel, errorChannel)
	}

	return recordChannel, errorChannel
}

// StreamProfileImportsV2WithMetadata returns response with metadata like status code and response headers
func (c *ApiService) StreamProfileImportsV2WithMetadata(StoreId string, params *ListProfileImportsV2Params) (*metadata.ResourceMetadata[chan string], chan error) {
	if params == nil {
		params = &ListProfileImportsV2Params{}
	}
	params.SetPageSize(client.ReadLimits(params.PageSize, params.Limit))

	recordChannel := make(chan string, 1)
	errorChannel := make(chan error, 1)

	response, err := c.PageProfileImportsV2WithMetadata(StoreId, params, "")
	if err != nil {
		errorChannel <- err
		close(recordChannel)
		close(errorChannel)
	} else {
		resource := response.GetResource()
		go c.streamProfileImportsV2(&resource, params, recordChannel, errorChannel)
	}

	metadataWrapper := metadata.NewResourceMetadata[chan string](
		recordChannel,            // The stream
		response.GetStatusCode(), // HTTP status code from page response
		response.GetHeaders(),    // HTTP headers from page response
	)

	return metadataWrapper, errorChannel
}

func (c *ApiService) streamProfileImportsV2(response *ListProfileImportsV0Response, params *ListProfileImportsV2Params, recordChannel chan string, errorChannel chan error) {
	curRecord := 1

	for response != nil {
		responseRecords := response.Imports
		for item := range responseRecords {
			recordChannel <- responseRecords[item]
			curRecord += 1
			if params.Limit != nil && *params.Limit < curRecord {
				close(recordChannel)
				close(errorChannel)
				return
			}
		}

		record, err := client.GetNext(c.baseURL+"/v1/Stores/{storeId}/Profiles/Imports", response, c.getNextListProfileImportsV0Response)
		if err != nil {
			errorChannel <- err
			break
		} else if record == nil {
			break
		}

		response = record.(*ListProfileImportsV0Response)
	}

	close(recordChannel)
	close(errorChannel)
}

func (c *ApiService) getNextListProfileImportsV0Response(nextPageUrl string) (interface{}, error) {
	if nextPageUrl == "" {
		return nil, nil
	}
	resp, err := c.requestHandler.Get(nextPageUrl, nil, nil, c.apiVersion)
	if err != nil {
		return nil, err
	}

	defer resp.Body.Close()

	ps := &ListProfileImportsV0Response{}
	if err := json.NewDecoder(resp.Body).Decode(ps); err != nil {
		return nil, err
	}
	return ps, nil
}
