/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Media
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package openapi

import (
	"time"
)

// MediaV1MediaProcessor struct for MediaV1MediaProcessor
type MediaV1MediaProcessor struct {
	// The SID of the Account that created the resource
	AccountSid *string `json:"account_sid,omitempty"`
	// The unique string that identifies the resource
	Sid *string `json:"sid,omitempty"`
	// The ISO 8601 date and time in GMT when the resource was created
	DateCreated *time.Time `json:"date_created,omitempty"`
	// The ISO 8601 date and time in GMT when the resource was last updated
	DateUpdated *time.Time `json:"date_updated,omitempty"`
	// The Media Extension name or URL
	Extension *string `json:"extension,omitempty"`
	// The Media Extension context
	ExtensionContext *string `json:"extension_context,omitempty"`
	Status           *string `json:"status,omitempty"`
	// The absolute URL of the resource
	Url *string `json:"url,omitempty"`
	// The reason why a MediaProcessor ended
	EndedReason *string `json:"ended_reason,omitempty"`
	// The URL to which Twilio will send MediaProcessor event updates
	StatusCallback *string `json:"status_callback,omitempty"`
	// The HTTP method Twilio should use to call the `status_callback` URL
	StatusCallbackMethod *string `json:"status_callback_method,omitempty"`
	// Maximum MediaProcessor duration in seconds
	MaxDuration *int `json:"max_duration,omitempty"`
}
