/*
 * Twilio - Messaging
 *
 * This is the public Twilio REST API.
 *
 * API version: 5.15.0
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// MessagingV1Service struct for MessagingV1Service
type MessagingV1Service struct {
	AccountSid string `json:"account_sid,omitempty"`
	AreaCodeGeomatch bool `json:"area_code_geomatch,omitempty"`
	DateCreated time.Time `json:"date_created,omitempty"`
	DateUpdated time.Time `json:"date_updated,omitempty"`
	FallbackMethod string `json:"fallback_method,omitempty"`
	FallbackToLongCode bool `json:"fallback_to_long_code,omitempty"`
	FallbackUrl string `json:"fallback_url,omitempty"`
	FriendlyName string `json:"friendly_name,omitempty"`
	InboundMethod string `json:"inbound_method,omitempty"`
	InboundRequestUrl string `json:"inbound_request_url,omitempty"`
	Links map[string]interface{} `json:"links,omitempty"`
	MmsConverter bool `json:"mms_converter,omitempty"`
	ScanMessageContent string `json:"scan_message_content,omitempty"`
	Sid string `json:"sid,omitempty"`
	SmartEncoding bool `json:"smart_encoding,omitempty"`
	StatusCallback string `json:"status_callback,omitempty"`
	StickySender bool `json:"sticky_sender,omitempty"`
	SynchronousValidation bool `json:"synchronous_validation,omitempty"`
	Url string `json:"url,omitempty"`
	ValidityPeriod int32 `json:"validity_period,omitempty"`
}
