/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio API definition for public-api voice
 * Powers Twilio public-api voice
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package openapi

import (
	"encoding/json"
	"net/url"
	"strings"

	"github.com/twilio/twilio-go/client/metadata"
)

// Optional parameters for the method 'CreateOrUpdateDefaultConfiguration'
type CreateOrUpdateDefaultConfigurationParams struct {
	//
	DefaultConfigurationRequest *DefaultConfigurationRequest `json:"DefaultConfigurationRequest,omitempty"`
}

func (params *CreateOrUpdateDefaultConfigurationParams) SetDefaultConfigurationRequest(DefaultConfigurationRequest DefaultConfigurationRequest) *CreateOrUpdateDefaultConfigurationParams {
	params.DefaultConfigurationRequest = &DefaultConfigurationRequest
	return params
}

func (c *ApiService) CreateOrUpdateDefaultConfiguration(Type string, params *CreateOrUpdateDefaultConfigurationParams) error {
	path := "/v2/Configurations/{Type}/Default"
	path = strings.Replace(path, "{"+"Type"+"}", Type, -1)

	data := url.Values{}
	headers := map[string]interface{}{
		"Content-Type": "application/json",
	}

	body := []byte{}
	if params != nil && params.DefaultConfigurationRequest != nil {
		b, err := json.Marshal(*params.DefaultConfigurationRequest)
		if err != nil {
			return err
		}
		body = b
	}

	resp, err := c.requestHandler.Post(c.baseURL+path, data, headers, c.apiVersion, body...)
	if err != nil {
		return err
	}

	defer resp.Body.Close()

	return nil
}

// CreateOrUpdateDefaultConfigurationWithMetadata returns response with metadata like status code and response headers
func (c *ApiService) CreateOrUpdateDefaultConfigurationWithMetadata(Type string, params *CreateOrUpdateDefaultConfigurationParams) (*metadata.ResourceMetadata[bool], error) {
	path := "/v2/Configurations/{Type}/Default"
	path = strings.Replace(path, "{"+"Type"+"}", Type, -1)

	data := url.Values{}
	headers := map[string]interface{}{
		"Content-Type": "application/json",
	}

	body := []byte{}
	if params != nil && params.DefaultConfigurationRequest != nil {
		b, err := json.Marshal(*params.DefaultConfigurationRequest)
		if err != nil {
			return nil, err
		}
		body = b
	}

	resp, err := c.requestHandler.Post(c.baseURL+path, data, headers, c.apiVersion, body...)
	if err != nil {
		return nil, err
	}

	defer resp.Body.Close()

	metadataWrapper := metadata.NewResourceMetadata[bool](
		true,            // The resource object
		resp.StatusCode, // HTTP status code
		resp.Header,     // HTTP headers
	)

	return metadataWrapper, nil
}

func (c *ApiService) FetchDefaultConfiguration(Type string) (*VoiceV2Response, error) {
	path := "/v2/Configurations/{Type}/Default"
	path = strings.Replace(path, "{"+"Type"+"}", Type, -1)

	data := url.Values{}
	headers := map[string]interface{}{
		"Content-Type": "application/x-www-form-urlencoded",
	}

	resp, err := c.requestHandler.Get(c.baseURL+path, data, headers, c.apiVersion)
	if err != nil {
		return nil, err
	}

	defer resp.Body.Close()

	ps := &VoiceV2Response{}
	if err := json.NewDecoder(resp.Body).Decode(ps); err != nil {
		return nil, err
	}

	return ps, err
}

// FetchDefaultConfigurationWithMetadata returns response with metadata like status code and response headers
func (c *ApiService) FetchDefaultConfigurationWithMetadata(Type string) (*metadata.ResourceMetadata[VoiceV2Response], error) {
	path := "/v2/Configurations/{Type}/Default"
	path = strings.Replace(path, "{"+"Type"+"}", Type, -1)

	data := url.Values{}
	headers := map[string]interface{}{
		"Content-Type": "application/x-www-form-urlencoded",
	}

	resp, err := c.requestHandler.Get(c.baseURL+path, data, headers, c.apiVersion)
	if err != nil {
		return nil, err
	}

	defer resp.Body.Close()

	ps := &VoiceV2Response{}
	if err := json.NewDecoder(resp.Body).Decode(ps); err != nil {
		return nil, err
	}

	metadataWrapper := metadata.NewResourceMetadata[VoiceV2Response](
		*ps,             // The resource object
		resp.StatusCode, // HTTP status code
		resp.Header,     // HTTP headers
	)

	return metadataWrapper, nil
}
