/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio API definition for public-api voice
 * Powers Twilio public-api voice
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package openapi

// VoiceV2CompositionPolicy The composition configuration for recordings.
type VoiceV2CompositionPolicy struct {
	// The number of channels to be composed.
	Channels *string `json:"channels,omitempty"`
	// Trim the silence in the recordings.
	Trim *string `json:"trim,omitempty"`
	// The audio track to record for the call.
	Track *string `json:"track,omitempty"`
}
