/*
 * Twilio - Wireless
 *
 * This is the public Twilio REST API.
 *
 * API version: 5.15.0
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// WirelessV1RatePlanReadResponse struct for WirelessV1RatePlanReadResponse
type WirelessV1RatePlanReadResponse struct {
	Meta WirelessV1CommandReadResponseMeta `json:"meta,omitempty"`
	RatePlans []WirelessV1RatePlan `json:"rate_plans,omitempty"`
}
