/*
 * Twilio - Pricing
 *
 * This is the public Twilio REST API.
 *
 * API version: 1.12.0
 * Contact: support@twilio.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

// PricingV1MessagingMessagingCountry struct for PricingV1MessagingMessagingCountry
type PricingV1MessagingMessagingCountry struct {
	// The name of the country
	Country *string `json:"Country,omitempty"`
	// The ISO country code
	IsoCountry *string `json:"IsoCountry,omitempty"`
	// The absolute URL of the resource
	Url *string `json:"Url,omitempty"`
}
