/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Accounts
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package openapi

import (
	"encoding/json"
	"net/url"
)

// Optional parameters for the method 'FetchMessagingGeopermissions'
type FetchMessagingGeopermissionsParams struct {
	// The country code to filter the geo permissions. If provided, only the geo permission for the specified country will be returned.
	CountryCode *string `json:"CountryCode,omitempty"`
}

func (params *FetchMessagingGeopermissionsParams) SetCountryCode(CountryCode string) *FetchMessagingGeopermissionsParams {
	params.CountryCode = &CountryCode
	return params
}

//
func (c *ApiService) FetchMessagingGeopermissions(params *FetchMessagingGeopermissionsParams) (*AccountsV1MessagingGeopermissions, error) {
	path := "/v1/Messaging/GeoPermissions"

	data := url.Values{}
	headers := map[string]interface{}{
		"Content-Type": "application/x-www-form-urlencoded",
	}

	if params != nil && params.CountryCode != nil {
		data.Set("CountryCode", *params.CountryCode)
	}

	resp, err := c.requestHandler.Get(c.baseURL+path, data, headers)
	if err != nil {
		return nil, err
	}

	defer resp.Body.Close()

	ps := &AccountsV1MessagingGeopermissions{}
	if err := json.NewDecoder(resp.Body).Decode(ps); err != nil {
		return nil, err
	}

	return ps, err
}

// Optional parameters for the method 'UpdateMessagingGeopermissions'
type UpdateMessagingGeopermissionsParams struct {
	// A list of objects where each object represents the Geo Permission to be updated. Each object contains the following fields: `country_code`, unique code for each country of Geo Permission; `type`, permission type of the Geo Permission i.e. country; `enabled`, configure true for enabling the Geo Permission, false for disabling the Geo Permission.
	Permissions *[]interface{} `json:"Permissions,omitempty"`
}

func (params *UpdateMessagingGeopermissionsParams) SetPermissions(Permissions []interface{}) *UpdateMessagingGeopermissionsParams {
	params.Permissions = &Permissions
	return params
}

//
func (c *ApiService) UpdateMessagingGeopermissions(params *UpdateMessagingGeopermissionsParams) (*AccountsV1MessagingGeopermissions, error) {
	path := "/v1/Messaging/GeoPermissions"

	data := url.Values{}
	headers := map[string]interface{}{
		"Content-Type": "application/x-www-form-urlencoded",
	}

	if params != nil && params.Permissions != nil {
		for _, item := range *params.Permissions {
			v, err := json.Marshal(item)

			if err != nil {
				return nil, err
			}

			data.Add("Permissions", string(v))
		}
	}

	resp, err := c.requestHandler.Patch(c.baseURL+path, data, headers)
	if err != nil {
		return nil, err
	}

	defer resp.Body.Close()

	ps := &AccountsV1MessagingGeopermissions{}
	if err := json.NewDecoder(resp.Body).Decode(ps); err != nil {
		return nil, err
	}

	return ps, err
}
