/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Sync
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package openapi

// SyncV1SyncMapPermission struct for SyncV1SyncMapPermission
type SyncV1SyncMapPermission struct {
	// The SID of the Account that created the resource
	AccountSid *string `json:"account_sid,omitempty"`
	// The SID of the Sync Service that the resource is associated with
	ServiceSid *string `json:"service_sid,omitempty"`
	// Sync Map SID
	MapSid *string `json:"map_sid,omitempty"`
	// The identity of the user to whom the Sync Document Permission applies
	Identity *string `json:"identity,omitempty"`
	// Read access
	Read *bool `json:"read,omitempty"`
	// Write access
	Write *bool `json:"write,omitempty"`
	// Manage access
	Manage *bool `json:"manage,omitempty"`
	// The absolute URL of the Sync Map Permission resource
	Url *string `json:"url,omitempty"`
}
