/*
 * Twilio - Preview
 *
 * This is the public Twilio REST API.
 *
 * API version: 5.15.0
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CreateSyncMapRequest struct for CreateSyncMapRequest
type CreateSyncMapRequest struct {
	UniqueName string `json:"UniqueName,omitempty"`
}
