/*
 * Twilio - Studio
 *
 * This is the public Twilio REST API.
 *
 * API version: 1.0.0
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package twilio
// InlineResponse200 struct for InlineResponse200
type InlineResponse200 struct {
	Flows []StudioV1Flow `json:"flows,omitempty"`
	Meta InlineResponse200Meta `json:"meta,omitempty"`
}
