/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Numbers
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package openapi

// ShortCodeApplicationResponsePage struct for ShortCodeApplicationResponsePage
type ShortCodeApplicationResponsePage struct {
	TotalElements int64 `json:"total_elements,omitempty"`
	TotalPages    int64 `json:"total_pages,omitempty"`
	CurrentPage   int   `json:"current_page,omitempty"`
	PerPage       int   `json:"per_page,omitempty"`
	HasNext       bool  `json:"has_next,omitempty"`
	HasPrev       bool  `json:"has_prev,omitempty"`
	// List of Short Code Applications.
	Results []ShortCodeApplication `json:"results,omitempty"`
}
