/*
 * Twilio - Numbers
 *
 * This is the public Twilio REST API.
 *
 * API version: 1.0.0
 * Contact: support@twilio.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"time"
)

// NumbersV2RegulatoryComplianceSupportingDocument struct for NumbersV2RegulatoryComplianceSupportingDocument
type NumbersV2RegulatoryComplianceSupportingDocument struct {
	AccountSid   *string                   `json:"account_sid,omitempty"`
	Attributes   *map[string]interface{}   `json:"attributes,omitempty"`
	DateCreated  *time.Time                `json:"date_created,omitempty"`
	DateUpdated  *time.Time                `json:"date_updated,omitempty"`
	FriendlyName *string                   `json:"friendly_name,omitempty"`
	MimeType     *string                   `json:"mime_type,omitempty"`
	Sid          *string                   `json:"sid,omitempty"`
	Status       *SupportingDocumentStatus `json:"status,omitempty"`
	Type         *string                   `json:"type,omitempty"`
	Url          *string                   `json:"url,omitempty"`
}
