/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Numbers
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package openapi

// CreateShortCodeApplicationBundleInquiryResponse struct for CreateShortCodeApplicationBundleInquiryResponse
type CreateShortCodeApplicationBundleInquiryResponse struct {
	// The unique identifier of the inquiry.
	InquiryId string `json:"inquiry_id,omitempty"`
	// The session token for the inquiry.
	InquirySessionToken string `json:"inquiry_session_token,omitempty"`
	// The unique identifier of the Short Code Application.
	ApplicationSid string `json:"application_sid,omitempty"`
	// The Bundle SID associated with the inquiry.
	BundleSid string `json:"bundle_sid,omitempty"`
}
