/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Conversations
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package openapi

// ConversationsV1ServiceConfiguration struct for ConversationsV1ServiceConfiguration
type ConversationsV1ServiceConfiguration struct {
	// The unique string that identifies the resource
	ChatServiceSid *string `json:"chat_service_sid,omitempty"`
	// The role assigned to a conversation creator user when they join a new conversation
	DefaultConversationCreatorRoleSid *string `json:"default_conversation_creator_role_sid,omitempty"`
	// The role assigned to users when they are added to a conversation
	DefaultConversationRoleSid *string `json:"default_conversation_role_sid,omitempty"`
	// The service role assigned to users when they are added to the service
	DefaultChatServiceRoleSid *string `json:"default_chat_service_role_sid,omitempty"`
	// An absolute URL for this service configuration.
	Url *string `json:"url,omitempty"`
	// Absolute URL to access the push notifications configuration of this service.
	Links *map[string]interface{} `json:"links,omitempty"`
	// Whether the Reachability Indicator feature is enabled for this Conversations Service
	ReachabilityEnabled *bool `json:"reachability_enabled,omitempty"`
}
