/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio API definition for public-api voice
 * Powers Twilio public-api voice
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package openapi

import (
	"time"
)

// VoiceV3Transcription struct for VoiceV3Transcription
type VoiceV3Transcription struct {
	// Unique identifier for a Transcription. This is also the transcriptionId returned in the LRO 202 response.
	Id string `json:"id"`
	// Twilio Account SID
	AccountId string `json:"accountId"`
	// The current status of the transcription operation
	Status string `json:"status"`
	// Unique identifier for a Transcription configuration.
	TranscriptionConfigurationId string `json:"transcriptionConfigurationId"`
	// The third party media URL
	MediaUrl *string `json:"mediaUrl,omitempty"`
	// The source ID (recording ID) - used for tracking only
	SourceId *string `json:"sourceId,omitempty"`
	// The call/recording start time. When the transcription was created using a sourceId, this value is inferred from the recording resource's start time. When created using a mediaUrl, this reflects the value supplied by the caller.
	AudioStartedAt time.Time `json:"audioStartedAt,omitempty"`
	// Maestro conversation ID, populated once the transcription has been stored in Maestro.
	ConversationId *string `json:"conversationId,omitempty"`
	// Array of participants in the conversation
	Participants []VoiceV3Participant `json:"participants,omitempty"`
	// Audio duration in seconds
	Duration              *int                         `json:"duration,omitempty"`
	ResolvedConfiguration VoiceV3ResolvedConfiguration `json:"resolvedConfiguration,omitempty"`
	// When this transcript was created
	CreatedAt time.Time `json:"createdAt"`
	// When this transcript was last updated
	UpdatedAt time.Time `json:"updatedAt"`
	// The URL of this resource
	Url string `json:"url"`
}
