/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Autopilot
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package openapi

// AutopilotV1TaskStatistics struct for AutopilotV1TaskStatistics
type AutopilotV1TaskStatistics struct {
	// The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the TaskStatistics resource.
	AccountSid *string `json:"account_sid,omitempty"`
	// The SID of the [Assistant](https://www.twilio.com/docs/autopilot/api/assistant) that is the parent of the Task associated with the resource.
	AssistantSid *string `json:"assistant_sid,omitempty"`
	// The SID of the [Task](https://www.twilio.com/docs/autopilot/api/task) for which the statistics were collected.
	TaskSid *string `json:"task_sid,omitempty"`
	// The total number of [Samples](https://www.twilio.com/docs/autopilot/api/task-sample) associated with the Task.
	SamplesCount *int `json:"samples_count,omitempty"`
	// The total number of [Fields](https://www.twilio.com/docs/autopilot/api/task-field) associated with the Task.
	FieldsCount *int `json:"fields_count,omitempty"`
	// The absolute URL of the TaskStatistics resource.
	Url *string `json:"url,omitempty"`
}
