/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Autopilot
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package openapi

// AutopilotV1Dialogue struct for AutopilotV1Dialogue
type AutopilotV1Dialogue struct {
	// The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Dialogue resource.
	AccountSid *string `json:"account_sid,omitempty"`
	// The SID of the [Assistant](https://www.twilio.com/docs/autopilot/api/assistant) that is the parent of the resource.
	AssistantSid *string `json:"assistant_sid,omitempty"`
	// The unique string that we created to identify the Dialogue resource.
	Sid *string `json:"sid,omitempty"`
	// The JSON string that describes the dialogue session object.
	Data *interface{} `json:"data,omitempty"`
	// The absolute URL of the Dialogue resource.
	Url *string `json:"url,omitempty"`
}
