/*
 * Twilio - Trunking
 *
 * This is the public Twilio REST API.
 *
 * API version: 1.8.0
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TrunkingV1TrunkRecording struct for TrunkingV1TrunkRecording
type TrunkingV1TrunkRecording struct {
	Mode RecordingMode `json:"Mode,omitempty"`
	Trim RecordingTrim `json:"Trim,omitempty"`
}
