/*
 * Twilio - Wireless
 *
 * This is the public Twilio REST API.
 *
 * API version: 1.0.0
 * Contact: support@twilio.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"time"
)

// WirelessV1RatePlan struct for WirelessV1RatePlan
type WirelessV1RatePlan struct {
	AccountSid                    *string    `json:"account_sid,omitempty"`
	DataEnabled                   *bool      `json:"data_enabled,omitempty"`
	DataLimit                     *int32     `json:"data_limit,omitempty"`
	DataMetering                  *string    `json:"data_metering,omitempty"`
	DateCreated                   *time.Time `json:"date_created,omitempty"`
	DateUpdated                   *time.Time `json:"date_updated,omitempty"`
	FriendlyName                  *string    `json:"friendly_name,omitempty"`
	InternationalRoaming          *[]string  `json:"international_roaming,omitempty"`
	InternationalRoamingDataLimit *int32     `json:"international_roaming_data_limit,omitempty"`
	MessagingEnabled              *bool      `json:"messaging_enabled,omitempty"`
	NationalRoamingDataLimit      *int32     `json:"national_roaming_data_limit,omitempty"`
	NationalRoamingEnabled        *bool      `json:"national_roaming_enabled,omitempty"`
	Sid                           *string    `json:"sid,omitempty"`
	UniqueName                    *string    `json:"unique_name,omitempty"`
	Url                           *string    `json:"url,omitempty"`
	VoiceEnabled                  *bool      `json:"voice_enabled,omitempty"`
}
