/*
 * Twilio - Video
 *
 * This is the public Twilio REST API.
 *
 * API version: 1.15.0
 * Contact: support@twilio.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

// RoomParticipantPublishedTrackKind the model 'RoomParticipantPublishedTrackKind'
type RoomParticipantPublishedTrackKind string

// List of room_participant_published_track_kind
const (
	ROOMPARTICIPANTPUBLISHEDTRACKKIND_AUDIO RoomParticipantPublishedTrackKind = "audio"
	ROOMPARTICIPANTPUBLISHEDTRACKKIND_VIDEO RoomParticipantPublishedTrackKind = "video"
	ROOMPARTICIPANTPUBLISHEDTRACKKIND_DATA  RoomParticipantPublishedTrackKind = "data"
)
