/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Studio
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package openapi

import (
	"time"
)

// StudioV1Engagement struct for StudioV1Engagement
type StudioV1Engagement struct {
	// The unique string that identifies the resource
	Sid *string `json:"sid,omitempty"`
	// The SID of the Account that created the resource
	AccountSid *string `json:"account_sid,omitempty"`
	// The SID of the Flow
	FlowSid *string `json:"flow_sid,omitempty"`
	// The SID of the Contact
	ContactSid *string `json:"contact_sid,omitempty"`
	// The phone number, SIP address or Client identifier that triggered this Engagement
	ContactChannelAddress *string `json:"contact_channel_address,omitempty"`
	// The current state of the execution flow
	Context *interface{} `json:"context,omitempty"`
	Status  *string      `json:"status,omitempty"`
	// The ISO 8601 date and time in GMT when the Engagement was created
	DateCreated *time.Time `json:"date_created,omitempty"`
	// The ISO 8601 date and time in GMT when the Engagement was last updated
	DateUpdated *time.Time `json:"date_updated,omitempty"`
	// The absolute URL of the resource
	Url *string `json:"url,omitempty"`
	// The URLs of the Engagement's nested resources
	Links *map[string]interface{} `json:"links,omitempty"`
}
