/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Assistants
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package openapi

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strings"

	"github.com/twilio/twilio-go/client"
	"github.com/twilio/twilio-go/client/metadata"
)

// get a session
func (c *ApiService) FetchSession(Id string) (*AssistantsV1Session, error) {
	path := "/v1/Sessions/{id}"
	path = strings.Replace(path, "{"+"id"+"}", Id, -1)

	data := url.Values{}
	headers := map[string]interface{}{
		"Content-Type": "application/x-www-form-urlencoded",
	}

	resp, err := c.requestHandler.Get(c.baseURL+path, data, headers)
	if err != nil {
		return nil, err
	}

	defer resp.Body.Close()

	ps := &AssistantsV1Session{}
	if err := json.NewDecoder(resp.Body).Decode(ps); err != nil {
		return nil, err
	}

	return ps, err
}

// FetchSessionWithMetadata returns response with metadata like status code and response headers
func (c *ApiService) FetchSessionWithMetadata(Id string) (*metadata.ResourceMetadata[AssistantsV1Session], error) {
	path := "/v1/Sessions/{id}"
	path = strings.Replace(path, "{"+"id"+"}", Id, -1)

	data := url.Values{}
	headers := map[string]interface{}{
		"Content-Type": "application/x-www-form-urlencoded",
	}

	resp, err := c.requestHandler.Get(c.baseURL+path, data, headers)
	if err != nil {
		return nil, err
	}

	defer resp.Body.Close()

	ps := &AssistantsV1Session{}
	if err := json.NewDecoder(resp.Body).Decode(ps); err != nil {
		return nil, err
	}

	metadataWrapper := metadata.NewResourceMetadata[AssistantsV1Session](
		*ps,             // The resource object
		resp.StatusCode, // HTTP status code
		resp.Header,     // HTTP headers
	)

	return metadataWrapper, nil
}

// Optional parameters for the method 'ListSessions'
type ListSessionsParams struct {
	// How many resources to return in each list page. The default is 50, and the maximum is 1000.
	PageSize *int `json:"PageSize,omitempty"`
	// Max number of records to return.
	Limit *int `json:"limit,omitempty"`
}

func (params *ListSessionsParams) SetPageSize(PageSize int) *ListSessionsParams {
	params.PageSize = &PageSize
	return params
}
func (params *ListSessionsParams) SetLimit(Limit int) *ListSessionsParams {
	params.Limit = &Limit
	return params
}

// Retrieve a single page of Sessions records from the API. Request is executed immediately.
func (c *ApiService) PageSessions(params *ListSessionsParams, pageToken, pageNumber string) (*ListSessionsResponse, error) {
	path := "/v1/Sessions"

	data := url.Values{}
	headers := map[string]interface{}{
		"Content-Type": "application/x-www-form-urlencoded",
	}

	if params != nil && params.PageSize != nil {
		data.Set("PageSize", fmt.Sprint(*params.PageSize))
	}

	if pageToken != "" {
		data.Set("PageToken", pageToken)
	}
	if pageNumber != "" {
		data.Set("Page", pageNumber)
	}

	resp, err := c.requestHandler.Get(c.baseURL+path, data, headers)
	if err != nil {
		return nil, err
	}

	defer resp.Body.Close()

	ps := &ListSessionsResponse{}
	if err := json.NewDecoder(resp.Body).Decode(ps); err != nil {
		return nil, err
	}

	return ps, err
}

// PageSessionsWithMetadata returns response with metadata like status code and response headers
func (c *ApiService) PageSessionsWithMetadata(params *ListSessionsParams, pageToken, pageNumber string) (*metadata.ResourceMetadata[ListSessionsResponse], error) {
	path := "/v1/Sessions"

	data := url.Values{}
	headers := map[string]interface{}{
		"Content-Type": "application/x-www-form-urlencoded",
	}

	if params != nil && params.PageSize != nil {
		data.Set("PageSize", fmt.Sprint(*params.PageSize))
	}

	if pageToken != "" {
		data.Set("PageToken", pageToken)
	}
	if pageNumber != "" {
		data.Set("Page", pageNumber)
	}

	resp, err := c.requestHandler.Get(c.baseURL+path, data, headers)
	if err != nil {
		return nil, err
	}

	defer resp.Body.Close()

	ps := &ListSessionsResponse{}
	if err := json.NewDecoder(resp.Body).Decode(ps); err != nil {
		return nil, err
	}

	metadataWrapper := metadata.NewResourceMetadata[ListSessionsResponse](
		*ps,             // The page object
		resp.StatusCode, // HTTP status code
		resp.Header,     // HTTP headers
	)

	return metadataWrapper, nil
}

// Lists Sessions records from the API as a list. Unlike stream, this operation is eager and loads 'limit' records into memory before returning.
func (c *ApiService) ListSessions(params *ListSessionsParams) ([]AssistantsV1Session, error) {
	response, errors := c.StreamSessions(params)

	records := make([]AssistantsV1Session, 0)
	for record := range response {
		records = append(records, record)
	}

	if err := <-errors; err != nil {
		return nil, err
	}

	return records, nil
}

// ListSessionsWithMetadata returns response with metadata like status code and response headers
func (c *ApiService) ListSessionsWithMetadata(params *ListSessionsParams) (*metadata.ResourceMetadata[[]AssistantsV1Session], error) {
	response, errors := c.StreamSessionsWithMetadata(params)
	resource := response.GetResource()

	records := make([]AssistantsV1Session, 0)
	for record := range resource {
		records = append(records, record)
	}

	if err := <-errors; err != nil {
		return nil, err
	}

	metadataWrapper := metadata.NewResourceMetadata[[]AssistantsV1Session](
		records,
		response.GetStatusCode(), // HTTP status code
		response.GetHeaders(),    // HTTP headers
	)

	return metadataWrapper, nil
}

// Streams Sessions records from the API as a channel stream. This operation lazily loads records as efficiently as possible until the limit is reached.
func (c *ApiService) StreamSessions(params *ListSessionsParams) (chan AssistantsV1Session, chan error) {
	if params == nil {
		params = &ListSessionsParams{}
	}
	params.SetPageSize(client.ReadLimits(params.PageSize, params.Limit))

	recordChannel := make(chan AssistantsV1Session, 1)
	errorChannel := make(chan error, 1)

	response, err := c.PageSessions(params, "", "")
	if err != nil {
		errorChannel <- err
		close(recordChannel)
		close(errorChannel)
	} else {
		go c.streamSessions(response, params, recordChannel, errorChannel)
	}

	return recordChannel, errorChannel
}

// StreamSessionsWithMetadata returns response with metadata like status code and response headers
func (c *ApiService) StreamSessionsWithMetadata(params *ListSessionsParams) (*metadata.ResourceMetadata[chan AssistantsV1Session], chan error) {
	if params == nil {
		params = &ListSessionsParams{}
	}
	params.SetPageSize(client.ReadLimits(params.PageSize, params.Limit))

	recordChannel := make(chan AssistantsV1Session, 1)
	errorChannel := make(chan error, 1)

	response, err := c.PageSessionsWithMetadata(params, "", "")
	if err != nil {
		errorChannel <- err
		close(recordChannel)
		close(errorChannel)
	} else {
		resource := response.GetResource()
		go c.streamSessions(&resource, params, recordChannel, errorChannel)
	}

	metadataWrapper := metadata.NewResourceMetadata[chan AssistantsV1Session](
		recordChannel,            // The stream
		response.GetStatusCode(), // HTTP status code from page response
		response.GetHeaders(),    // HTTP headers from page response
	)

	return metadataWrapper, errorChannel
}

func (c *ApiService) streamSessions(response *ListSessionsResponse, params *ListSessionsParams, recordChannel chan AssistantsV1Session, errorChannel chan error) {
	curRecord := 1

	for response != nil {
		responseRecords := response.Sessions
		for item := range responseRecords {
			recordChannel <- responseRecords[item]
			curRecord += 1
			if params.Limit != nil && *params.Limit < curRecord {
				close(recordChannel)
				close(errorChannel)
				return
			}
		}

		record, err := client.GetNext(c.baseURL, response, c.getNextListSessionsResponse)
		if err != nil {
			errorChannel <- err
			break
		} else if record == nil {
			break
		}

		response = record.(*ListSessionsResponse)
	}

	close(recordChannel)
	close(errorChannel)
}

func (c *ApiService) getNextListSessionsResponse(nextPageUrl string) (interface{}, error) {
	if nextPageUrl == "" {
		return nil, nil
	}
	resp, err := c.requestHandler.Get(nextPageUrl, nil, nil)
	if err != nil {
		return nil, err
	}

	defer resp.Body.Close()

	ps := &ListSessionsResponse{}
	if err := json.NewDecoder(resp.Body).Decode(ps); err != nil {
		return nil, err
	}
	return ps, nil
}
