/*
 * Twilio - Verify
 *
 * This is the public Twilio REST API.
 *
 * API version: 5.15.0
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// VerifyV2ServiceEntityFactorReadResponse struct for VerifyV2ServiceEntityFactorReadResponse
type VerifyV2ServiceEntityFactorReadResponse struct {
	Factors []VerifyV2ServiceEntityFactor `json:"Factors,omitempty"`
	Meta VerifyV2ServiceReadResponseMeta `json:"Meta,omitempty"`
}
