/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Verify
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package openapi

import (
	"time"
)

// VerifyV2Notification struct for VerifyV2Notification
type VerifyV2Notification struct {
	// A string that uniquely identifies this Notification.
	Sid *string `json:"sid,omitempty"`
	// Account Sid.
	AccountSid *string `json:"account_sid,omitempty"`
	// Service Sid.
	ServiceSid *string `json:"service_sid,omitempty"`
	// Entity Sid.
	EntitySid *string `json:"entity_sid,omitempty"`
	// Unique external identifier of the Entity
	Identity *string `json:"identity,omitempty"`
	// Challenge Sid.
	ChallengeSid *string `json:"challenge_sid,omitempty"`
	// The priority of the notification.
	Priority *string `json:"priority,omitempty"`
	// How long, in seconds, the notification is valid.
	Ttl *int `json:"ttl,omitempty"`
	// The date this Notification was created
	DateCreated *time.Time `json:"date_created,omitempty"`
}
