/*
 * Twilio - Ip_messaging
 *
 * This is the public Twilio REST API.
 *
 * API version: 5.15.0
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// IpMessagingV1ServiceChannelMemberReadResponse struct for IpMessagingV1ServiceChannelMemberReadResponse
type IpMessagingV1ServiceChannelMemberReadResponse struct {
	Members []IpMessagingV1ServiceChannelMember `json:"Members,omitempty"`
	Meta IpMessagingV1CredentialReadResponseMeta `json:"Meta,omitempty"`
}
