/*
 * Twilio - Messaging
 *
 * This is the public Twilio REST API.
 *
 * API version: 0.1.1
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// MessagingV1Deactivation struct for MessagingV1Deactivation
type MessagingV1Deactivation struct {
	RedirectTo string `json:"RedirectTo,omitempty"`
}
