/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Conversation Orchestrator
 * Manage configurations, conversations, participants, and communications. Create configurations to define capture rules and channel settings, then use conversations to group related communications.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package openapi

// ConversationsV2StartConversationRequest Creates a Conversation from a Participant roster and dispatches one action on it.
type ConversationsV2StartConversationRequest struct {
	// Configuration governing grouping, timeouts, and channel configuration.
	ConfigurationId string `json:"configurationId"`
	// Human-readable name for the Conversation.
	Name string `json:"name,omitempty"`
	// Everyone taking part. The dispatched action selects its actors from this roster.
	Participants  []ConversationsV2StartConversationParticipant `json:"participants"`
	Action        ConversationsV2StartConversationActionRequest `json:"action"`
	Configuration ConversationsV2StartConversationConfiguration `json:"configuration,omitempty"`
}
