/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Conversation Orchestrator
 * Manage configurations, conversations, participants, and communications. Create configurations to define capture rules and channel settings, then use conversations to group related communications.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package openapi

import (
	"time"
)

// ConversationsV2StartConversationAction The Action created by the StartConversation action. Type-less: the created Conversation and downstream channel identifiers live in the `related` map (not at the top level) so they remain valid across the full lifecycle.
type ConversationsV2StartConversationAction struct {
	// Unique identifier for this Action.
	Id     string                      `json:"id"`
	Status ConversationsV2ActionStatus `json:"status"`
	// Named identifiers, populated as the asynchronous work completes: - conversationId: The created Conversation (present once the Conversation is created) - channelId: The downstream channel identifier (present once dispatch succeeds) - executionSid: VOICE only. The Studio Flow execution that placed the call - callId: VOICE only. The Call SID of the outbound call  Absent from the 202 response (returned as an empty map).
	Related map[string]string `json:"related,omitempty"`
	// Timestamp when the Action was created.
	CreatedAt time.Time `json:"createdAt"`
	// Timestamp when the Action was last updated.
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	// Timestamp when the Action reached a terminal status. Null until the Action reaches one.
	CompletedAt *time.Time `json:"completedAt,omitempty"`
	// Human-readable failure reason. Null unless status is FAILED.
	FailureReason *string `json:"failureReason,omitempty"`
}
