/*
 * Twilio - Preview
 *
 * This is the public Twilio REST API.
 *
 * API version: 1.0.0
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ListFieldTypeResponse struct for ListFieldTypeResponse
type ListFieldTypeResponse struct {
	FieldTypes []PreviewUnderstandAssistantFieldType `json:"FieldTypes,omitempty"`
	Meta ListDayResponseMeta `json:"Meta,omitempty"`
}
