/*
 * Twilio - Accounts
 *
 * This is the public Twilio REST API.
 *
 * API version: 5.15.0
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// AccountsV1CredentialCredentialPublicKeyReadResponse struct for AccountsV1CredentialCredentialPublicKeyReadResponse
type AccountsV1CredentialCredentialPublicKeyReadResponse struct {
	Credentials []AccountsV1CredentialCredentialPublicKey `json:"credentials,omitempty"`
	Meta AccountsV1CredentialCredentialAwsReadResponseMeta `json:"meta,omitempty"`
}
