/*
 * Twilio - Flex
 *
 * This is the public Twilio REST API.
 *
 * API version: 1.12.0
 * Contact: support@twilio.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

// ListChannelResponseMeta struct for ListChannelResponseMeta
type ListChannelResponseMeta struct {
	FirstPageUrl    string `json:"FirstPageUrl,omitempty"`
	Key             string `json:"Key,omitempty"`
	NextPageUrl     string `json:"NextPageUrl,omitempty"`
	Page            int32  `json:"Page,omitempty"`
	PageSize        int32  `json:"PageSize,omitempty"`
	PreviousPageUrl string `json:"PreviousPageUrl,omitempty"`
	Url             string `json:"Url,omitempty"`
}
