/*
 * Twilio - Messaging
 *
 * This is the public Twilio REST API.
 *
 * API version: 5.15.0
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// MessagingV1ServiceAlphaSender struct for MessagingV1ServiceAlphaSender
type MessagingV1ServiceAlphaSender struct {
	AccountSid string `json:"AccountSid,omitempty"`
	AlphaSender string `json:"AlphaSender,omitempty"`
	Capabilities []string `json:"Capabilities,omitempty"`
	DateCreated time.Time `json:"DateCreated,omitempty"`
	DateUpdated time.Time `json:"DateUpdated,omitempty"`
	ServiceSid string `json:"ServiceSid,omitempty"`
	Sid string `json:"Sid,omitempty"`
	Url string `json:"Url,omitempty"`
}
