/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Insights
 * The Twilio Insights v3 API provides semantic query access to Conversations analytics data. Resources include synchronous Query, Metadata, and asynchronous QueryJobs for long-running queries.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package openapi

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strings"

	"github.com/twilio/twilio-go/client"
	"github.com/twilio/twilio-go/client/metadata"
)

// Optional parameters for the method 'CreateQueryJob'
type CreateQueryJobParams struct {
	// A client-generated UUIDv7 key that ensures idempotent behavior. Submitting the same key with an identical request returns the same operation without re-execution. Scoped to Account + Region. Retained for 24 hours.
	IdempotencyKey *string `json:"Idempotency-Key,omitempty"`
	//
	InsightsQueryRequest *InsightsQueryRequest `json:"InsightsQueryRequest,omitempty"`
}

func (params *CreateQueryJobParams) SetIdempotencyKey(IdempotencyKey string) *CreateQueryJobParams {
	params.IdempotencyKey = &IdempotencyKey
	return params
}
func (params *CreateQueryJobParams) SetInsightsQueryRequest(InsightsQueryRequest InsightsQueryRequest) *CreateQueryJobParams {
	params.InsightsQueryRequest = &InsightsQueryRequest
	return params
}

// Submit a long-running semantic query against the Conversations domain. Returns 202 Accepted with an operationId and a Location header pointing to the QueryJobs status endpoint for polling.
func (c *ApiService) CreateQueryJob(params *CreateQueryJobParams) (*QueryJobSubmitResponse, error) {
	path := "/v3/InsightsDomains/Conversations/QueryJobs"

	data := url.Values{}
	headers := map[string]interface{}{
		"Content-Type": "application/json",
	}

	body := []byte{}
	if params != nil && params.InsightsQueryRequest != nil {
		b, err := json.Marshal(*params.InsightsQueryRequest)
		if err != nil {
			return nil, err
		}
		body = b
	}

	if params != nil && params.IdempotencyKey != nil {
		headers["Idempotency-Key"] = *params.IdempotencyKey
	}
	resp, err := c.requestHandler.Post(c.baseURL+path, data, headers, c.apiVersion, body...)
	if err != nil {
		return nil, err
	}

	defer resp.Body.Close()

	ps := &QueryJobSubmitResponse{}
	if err := json.NewDecoder(resp.Body).Decode(ps); err != nil {
		return nil, err
	}

	return ps, err
}

// CreateQueryJobWithMetadata returns response with metadata like status code and response headers
func (c *ApiService) CreateQueryJobWithMetadata(params *CreateQueryJobParams) (*metadata.ResourceMetadata[QueryJobSubmitResponse], error) {
	path := "/v3/InsightsDomains/Conversations/QueryJobs"

	data := url.Values{}
	headers := map[string]interface{}{
		"Content-Type": "application/json",
	}

	body := []byte{}
	if params != nil && params.InsightsQueryRequest != nil {
		b, err := json.Marshal(*params.InsightsQueryRequest)
		if err != nil {
			return nil, err
		}
		body = b
	}

	if params != nil && params.IdempotencyKey != nil {
		headers["Idempotency-Key"] = *params.IdempotencyKey
	}
	resp, err := c.requestHandler.Post(c.baseURL+path, data, headers, c.apiVersion, body...)
	if err != nil {
		return nil, err
	}

	defer resp.Body.Close()

	ps := &QueryJobSubmitResponse{}
	if err := json.NewDecoder(resp.Body).Decode(ps); err != nil {
		return nil, err
	}

	metadataWrapper := metadata.NewResourceMetadata[QueryJobSubmitResponse](
		*ps,             // The resource object
		resp.StatusCode, // HTTP status code
		resp.Header,     // HTTP headers
	)

	return metadataWrapper, nil
}

// Poll the operation status. When status is COMPLETED, the response includes query results inline. When FAILED, the response includes error details conforming to the OperationError schema.
func (c *ApiService) FetchQueryJobStatus(OperationId string) (*QueryJobStatusResponse, error) {
	path := "/v3/InsightsDomains/Conversations/QueryJobs/{operationId}"
	path = strings.Replace(path, "{"+"operationId"+"}", OperationId, -1)

	data := url.Values{}
	headers := map[string]interface{}{
		"Content-Type": "application/x-www-form-urlencoded",
	}

	resp, err := c.requestHandler.Get(c.baseURL+path, data, headers, c.apiVersion)
	if err != nil {
		return nil, err
	}

	defer resp.Body.Close()

	ps := &QueryJobStatusResponse{}
	if err := json.NewDecoder(resp.Body).Decode(ps); err != nil {
		return nil, err
	}

	return ps, err
}

// FetchQueryJobStatusWithMetadata returns response with metadata like status code and response headers
func (c *ApiService) FetchQueryJobStatusWithMetadata(OperationId string) (*metadata.ResourceMetadata[QueryJobStatusResponse], error) {
	path := "/v3/InsightsDomains/Conversations/QueryJobs/{operationId}"
	path = strings.Replace(path, "{"+"operationId"+"}", OperationId, -1)

	data := url.Values{}
	headers := map[string]interface{}{
		"Content-Type": "application/x-www-form-urlencoded",
	}

	resp, err := c.requestHandler.Get(c.baseURL+path, data, headers, c.apiVersion)
	if err != nil {
		return nil, err
	}

	defer resp.Body.Close()

	ps := &QueryJobStatusResponse{}
	if err := json.NewDecoder(resp.Body).Decode(ps); err != nil {
		return nil, err
	}

	metadataWrapper := metadata.NewResourceMetadata[QueryJobStatusResponse](
		*ps,             // The resource object
		resp.StatusCode, // HTTP status code
		resp.Header,     // HTTP headers
	)

	return metadataWrapper, nil
}

// Optional parameters for the method 'ListQueryJobs'
type ListQueryJobsParams struct {
	// The maximum number of resources to return
	PageSize *int `json:"pageSize,omitempty"`
	// Token for pagination
	PageToken *string `json:"pageToken,omitempty"`
	// The operation status to filter results by.
	Status *LongRunningOperationStatus `json:"status,omitempty"`
	// Max number of records to return.
	Limit *int `json:"limit,omitempty"`
}

func (params *ListQueryJobsParams) SetPageSize(PageSize int) *ListQueryJobsParams {
	params.PageSize = &PageSize
	return params
}
func (params *ListQueryJobsParams) SetPageToken(PageToken string) *ListQueryJobsParams {
	params.PageToken = &PageToken
	return params
}
func (params *ListQueryJobsParams) SetStatus(Status LongRunningOperationStatus) *ListQueryJobsParams {
	params.Status = &Status
	return params
}
func (params *ListQueryJobsParams) SetLimit(Limit int) *ListQueryJobsParams {
	params.Limit = &Limit
	return params
}

// Retrieve a single page of QueryJobs records from the API. Request is executed immediately.
func (c *ApiService) PageQueryJobs(params *ListQueryJobsParams, pageToken string) (*QueryJobListResponse, error) {
	path := "/v3/InsightsDomains/Conversations/QueryJobs"

	data := url.Values{}
	headers := map[string]interface{}{
		"Content-Type": "application/x-www-form-urlencoded",
	}

	if params != nil && params.PageSize != nil {
		data.Set("pageSize", fmt.Sprint(*params.PageSize))
	}
	if params != nil && params.PageToken != nil {
		data.Set("pageToken", *params.PageToken)
	}
	if params != nil && params.Status != nil {
		data.Set("status", fmt.Sprint(*params.Status))
	}

	if pageToken != "" {
		data.Set("PageToken", pageToken)
	}

	resp, err := c.requestHandler.Get(c.baseURL+path, data, headers, c.apiVersion)
	if err != nil {
		return nil, err
	}

	defer resp.Body.Close()

	ps := &QueryJobListResponse{}
	if err := json.NewDecoder(resp.Body).Decode(ps); err != nil {
		return nil, err
	}

	return ps, err
}

// PageQueryJobsWithMetadata returns response with metadata like status code and response headers
func (c *ApiService) PageQueryJobsWithMetadata(params *ListQueryJobsParams, pageToken string) (*metadata.ResourceMetadata[QueryJobListResponse], error) {
	path := "/v3/InsightsDomains/Conversations/QueryJobs"

	data := url.Values{}
	headers := map[string]interface{}{
		"Content-Type": "application/x-www-form-urlencoded",
	}

	if params != nil && params.PageSize != nil {
		data.Set("pageSize", fmt.Sprint(*params.PageSize))
	}
	if params != nil && params.PageToken != nil {
		data.Set("pageToken", *params.PageToken)
	}
	if params != nil && params.Status != nil {
		data.Set("status", fmt.Sprint(*params.Status))
	}

	if pageToken != "" {
		data.Set("PageToken", pageToken)
	}

	resp, err := c.requestHandler.Get(c.baseURL+path, data, headers, c.apiVersion)
	if err != nil {
		return nil, err
	}

	defer resp.Body.Close()

	ps := &QueryJobListResponse{}
	if err := json.NewDecoder(resp.Body).Decode(ps); err != nil {
		return nil, err
	}

	metadataWrapper := metadata.NewResourceMetadata[QueryJobListResponse](
		*ps,             // The page object
		resp.StatusCode, // HTTP status code
		resp.Header,     // HTTP headers
	)

	return metadataWrapper, nil
}

// Lists QueryJobs records from the API as a list. Unlike stream, this operation is eager and loads 'limit' records into memory before returning.
func (c *ApiService) ListQueryJobs(params *ListQueryJobsParams) ([]QueryJobStatusResponse, error) {
	response, errors := c.StreamQueryJobs(params)

	records := make([]QueryJobStatusResponse, 0)
	for record := range response {
		records = append(records, record)
	}

	if err := <-errors; err != nil {
		return nil, err
	}

	return records, nil
}

// ListQueryJobsWithMetadata returns response with metadata like status code and response headers
func (c *ApiService) ListQueryJobsWithMetadata(params *ListQueryJobsParams) (*metadata.ResourceMetadata[[]QueryJobStatusResponse], error) {
	response, errors := c.StreamQueryJobsWithMetadata(params)
	resource := response.GetResource()

	records := make([]QueryJobStatusResponse, 0)
	for record := range resource {
		records = append(records, record)
	}

	if err := <-errors; err != nil {
		return nil, err
	}

	metadataWrapper := metadata.NewResourceMetadata[[]QueryJobStatusResponse](
		records,
		response.GetStatusCode(), // HTTP status code
		response.GetHeaders(),    // HTTP headers
	)

	return metadataWrapper, nil
}

// Streams QueryJobs records from the API as a channel stream. This operation lazily loads records as efficiently as possible until the limit is reached.
func (c *ApiService) StreamQueryJobs(params *ListQueryJobsParams) (chan QueryJobStatusResponse, chan error) {
	if params == nil {
		params = &ListQueryJobsParams{}
	}
	params.SetPageSize(client.ReadLimits(params.PageSize, params.Limit))

	recordChannel := make(chan QueryJobStatusResponse, 1)
	errorChannel := make(chan error, 1)

	response, err := c.PageQueryJobs(params, "")
	if err != nil {
		errorChannel <- err
		close(recordChannel)
		close(errorChannel)
	} else {
		path := "/v3/InsightsDomains/Conversations/QueryJobs"
		go c.streamQueryJobs(response, path, params, recordChannel, errorChannel)
	}

	return recordChannel, errorChannel
}

// StreamQueryJobsWithMetadata returns response with metadata like status code and response headers
func (c *ApiService) StreamQueryJobsWithMetadata(params *ListQueryJobsParams) (*metadata.ResourceMetadata[chan QueryJobStatusResponse], chan error) {
	if params == nil {
		params = &ListQueryJobsParams{}
	}
	params.SetPageSize(client.ReadLimits(params.PageSize, params.Limit))

	recordChannel := make(chan QueryJobStatusResponse, 1)
	errorChannel := make(chan error, 1)

	response, err := c.PageQueryJobsWithMetadata(params, "")
	if err != nil {
		errorChannel <- err
		close(recordChannel)
		close(errorChannel)
	} else {
		resource := response.GetResource()
		path := "/v3/InsightsDomains/Conversations/QueryJobs"
		go c.streamQueryJobs(&resource, path, params, recordChannel, errorChannel)
	}

	metadataWrapper := metadata.NewResourceMetadata[chan QueryJobStatusResponse](
		recordChannel,            // The stream
		response.GetStatusCode(), // HTTP status code from page response
		response.GetHeaders(),    // HTTP headers from page response
	)

	return metadataWrapper, errorChannel
}

func (c *ApiService) streamQueryJobs(response *QueryJobListResponse, path string, params *ListQueryJobsParams, recordChannel chan QueryJobStatusResponse, errorChannel chan error) {
	curRecord := 1

	for response != nil {
		responseRecords := response.Items
		for item := range responseRecords {
			recordChannel <- responseRecords[item]
			curRecord += 1
			if params.Limit != nil && *params.Limit < curRecord {
				close(recordChannel)
				close(errorChannel)
				return
			}
		}

		record, err := client.GetNext(c.baseURL+path, response, c.getNextQueryJobListResponse)
		if err != nil {
			errorChannel <- err
			break
		} else if record == nil {
			break
		}

		response = record.(*QueryJobListResponse)
	}

	close(recordChannel)
	close(errorChannel)
}

func (c *ApiService) getNextQueryJobListResponse(nextPageUrl string) (interface{}, error) {
	if nextPageUrl == "" {
		return nil, nil
	}
	resp, err := c.requestHandler.Get(nextPageUrl, nil, nil, c.apiVersion)
	if err != nil {
		return nil, err
	}

	defer resp.Body.Close()

	ps := &QueryJobListResponse{}
	if err := json.NewDecoder(resp.Body).Decode(ps); err != nil {
		return nil, err
	}
	return ps, nil
}
