/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio Knowledge API
 * APIs for managing knowledge bases and knowledge content for AI-powered applications.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package openapi

import (
	"time"
)

// KnowledgeBase struct for KnowledgeBase
type KnowledgeBase struct {
	// Provides a unique and addressable name to be assigned to this Knowledge Base. This name is assigned by the developer and can be used in addition to the ID. It is intended to be human-readable and unique within the account.
	DisplayName string `json:"displayName"`
	// A human readable description of this resource, up to 128 characters.
	Description string `json:"description,omitempty"`
	// The unique identifier for the Knowledge Base
	Id string `json:"id"`
	// The provisioning status of the Knowledge Base
	Status string `json:"status"`
	// The ISO 8601 timestamp when the Knowledge Base was created.
	CreatedAt time.Time `json:"createdAt"`
	// The ISO 8601 timestamp when the Knowledge Base was last updated.
	UpdatedAt time.Time `json:"updatedAt"`
	// The current version number of the Knowledge Base. Incremented on each successful mutable update.
	Version int `json:"version"`
}
