/*
 * Twilio - Pricing
 *
 * This is the public Twilio REST API.
 *
 * API version: 1.11.0
 * Contact: support@twilio.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

// PricingV2VoiceVoiceNumberInboundCallPrice The InboundCallPrice record
type PricingV2VoiceVoiceNumberInboundCallPrice struct {
	BasePrice    float32 `json:"BasePrice,omitempty"`
	CurrentPrice float32 `json:"CurrentPrice,omitempty"`
	NumberType   string  `json:"NumberType,omitempty"`
}
