/*
 * Twilio - Studio
 *
 * This is the public Twilio REST API.
 *
 * API version: 1.10.0
 * Contact: support@twilio.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"time"
)

// StudioV2Flow struct for StudioV2Flow
type StudioV2Flow struct {
	// The SID of the Account that created the resource
	AccountSid *string `json:"AccountSid,omitempty"`
	// Description of change made in the revision
	CommitMessage *string `json:"CommitMessage,omitempty"`
	// The ISO 8601 date and time in GMT when the resource was created
	DateCreated *time.Time `json:"DateCreated,omitempty"`
	// The ISO 8601 date and time in GMT when the resource was last updated
	DateUpdated *time.Time `json:"DateUpdated,omitempty"`
	// JSON representation of flow definition
	Definition *map[string]interface{} `json:"Definition,omitempty"`
	// List of error in the flow definition
	Errors *[]map[string]interface{} `json:"Errors,omitempty"`
	// The string that you assigned to describe the Flow
	FriendlyName *string `json:"FriendlyName,omitempty"`
	// Nested resource URLs
	Links *map[string]interface{} `json:"Links,omitempty"`
	// The latest revision number of the Flow's definition
	Revision *int32 `json:"Revision,omitempty"`
	// The unique string that identifies the resource
	Sid *string `json:"Sid,omitempty"`
	// The status of the Flow
	Status *string `json:"Status,omitempty"`
	// The absolute URL of the resource
	Url *string `json:"Url,omitempty"`
	// Boolean if the flow definition is valid
	Valid *bool `json:"Valid,omitempty"`
	// List of warnings in the flow definition
	Warnings   *[]map[string]interface{} `json:"Warnings,omitempty"`
	WebhookUrl *string                   `json:"WebhookUrl,omitempty"`
}
