/*
 * Twilio - Supersim
 *
 * This is the public Twilio REST API.
 *
 * API version: 1.8.0
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Status the model 'Status'
type Status string

// List of status
const (
	NEW Status = "new"
	READY Status = "ready"
	ACTIVE Status = "active"
	INACTIVE Status = "inactive"
	SCHEDULED Status = "scheduled"
)
