/*
 * Twilio - Supersim
 *
 * This is the public Twilio REST API.
 *
 * API version: 1.0.0
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ListNetworkResponse struct for ListNetworkResponse
type ListNetworkResponse struct {
	Meta ListCommandResponseMeta `json:"Meta,omitempty"`
	Networks []SupersimV1Network `json:"Networks,omitempty"`
}
