/*
 * Twilio - Chat
 *
 * This is the public Twilio REST API.
 *
 * API version: 5.15.0
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineObject2 struct for InlineObject2
type InlineObject2 struct {
	// A descriptive string that you create to describe the new resource.
	FriendlyName string `json:"FriendlyName"`
}
