/*
 * Twilio - Verify
 *
 * This is the public Twilio REST API.
 *
 * API version: 1.11.0
 * Contact: support@twilio.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"time"
)

// VerifyV2ServiceEntityFactor struct for VerifyV2ServiceEntityFactor
type VerifyV2ServiceEntityFactor struct {
	// Account Sid.
	AccountSid *string `json:"AccountSid,omitempty"`
	// Configurations for a `factor_type`.
	Config *map[string]interface{} `json:"Config,omitempty"`
	// The date this Factor was created
	DateCreated *time.Time `json:"DateCreated,omitempty"`
	// The date this Factor was updated
	DateUpdated *time.Time `json:"DateUpdated,omitempty"`
	// Entity Sid.
	EntitySid *string `json:"EntitySid,omitempty"`
	// The Type of this Factor
	FactorType *string `json:"FactorType,omitempty"`
	// A human readable description of this resource.
	FriendlyName *string `json:"FriendlyName,omitempty"`
	// Unique external identifier of the Entity
	Identity *string `json:"Identity,omitempty"`
	// Service Sid.
	ServiceSid *string `json:"ServiceSid,omitempty"`
	// A string that uniquely identifies this Factor.
	Sid *string `json:"Sid,omitempty"`
	// The Status of this Factor
	Status *string `json:"Status,omitempty"`
	// The URL of this resource.
	Url *string `json:"Url,omitempty"`
}
