/*
 * Twilio - Verify
 *
 * This is the public Twilio REST API.
 *
 * API version: 0.1.1
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// VerifyV2ServiceVerificationCheck struct for VerifyV2ServiceVerificationCheck
type VerifyV2ServiceVerificationCheck struct {
	AccountSid  string    `json:"AccountSid,omitempty"`
	Amount      string    `json:"Amount,omitempty"`
	Channel     Channel   `json:"Channel,omitempty"`
	DateCreated time.Time `json:"DateCreated,omitempty"`
	DateUpdated time.Time `json:"DateUpdated,omitempty"`
	Payee       string    `json:"Payee,omitempty"`
	ServiceSid  string    `json:"ServiceSid,omitempty"`
	Sid         string    `json:"Sid,omitempty"`
	Status      string    `json:"Status,omitempty"`
	To          string    `json:"To,omitempty"`
	Valid       bool      `json:"Valid,omitempty"`
}
