/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Lookups
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package openapi

// Metadata struct for Metadata
type Metadata struct {
	// Token for the next page of results
	NextPageToken string `json:"NextPageToken,omitempty"`
	// Token for the previous page of results
	PreviousPageToken string `json:"PreviousPageToken,omitempty"`
	// Key for the list of log entries
	ListKey string `json:"ListKey,omitempty"`
	// Number of log entries in the current page
	PageSize int `json:"PageSize,omitempty"`
	// Indicates if the token is direct
	DirectToken bool `json:"DirectToken,omitempty"`
}
