name: Run Tests
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run automatically at 8AM PST Monday-Friday
    - cron: '0 15 * * 1-5'
  workflow_dispatch:

jobs:
  tests:
    name: Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        go: [ '1.15', '1.16' ]
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v2

      - name: Checkout twilio-go
        uses: actions/checkout@v2

      - name: Build
        run: make install

      - name: Run Unit Tests
        run: make test

      - name: Run Cluster Tests
        if: ${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging') && github.event_name != 'pull_request' }}
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_FROM_NUMBER: ${{ secrets.TWILIO_FROM_NUMBER }}
          TWILIO_TO_NUMBER: ${{ secrets.TWILIO_TO_NUMBER }}
        run: make cluster-test

  notify-on-failure:
    name: Slack notify on failure
    if: ${{ failure() && github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
    needs: [ tests ]
    runs-on: ubuntu-latest
    steps:
      - uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: 'danger'
          SLACK_ICON_EMOJI: ':github:'
          SLACK_MESSAGE: ${{ format('Failed running build on {1}{3} {0}/{1}/actions/runs/{2}', github.server_url, github.repository, github.run_id, ':') }}
          SLACK_TITLE: Build Failure
          SLACK_USERNAME: GitHub Actions
          SLACK_MSG_AUTHOR: twilio-dx
          SLACK_FOOTER: Posted automatically using GitHub Actions
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          MSG_MINIMAL: true
