/*
 * Twilio - Flex
 *
 * This is the public Twilio REST API.
 *
 * API version: 5.15.0
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// FlexV1FlexFlowReadResponse struct for FlexV1FlexFlowReadResponse
type FlexV1FlexFlowReadResponse struct {
	FlexFlows []FlexV1FlexFlow `json:"FlexFlows,omitempty"`
	Meta FlexV1ChannelReadResponseMeta `json:"Meta,omitempty"`
}
