/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Messaging
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package openapi

import (
	"encoding/json"
	"net/url"
	"strings"

	"github.com/twilio/twilio-go/client/metadata"
)

//
func (c *ApiService) FetchDomainCertV4(DomainSid string) (*MessagingV2DomainCertV4, error) {
	path := "/v2/LinkShortening/Domains/{DomainSid}/Certificate"
	path = strings.Replace(path, "{"+"DomainSid"+"}", DomainSid, -1)

	data := url.Values{}
	headers := map[string]interface{}{
		"Content-Type": "application/x-www-form-urlencoded",
	}

	resp, err := c.requestHandler.Get(c.baseURL+path, data, headers)
	if err != nil {
		return nil, err
	}

	defer resp.Body.Close()

	ps := &MessagingV2DomainCertV4{}
	if err := json.NewDecoder(resp.Body).Decode(ps); err != nil {
		return nil, err
	}

	return ps, err
}

// FetchDomainCertV4WithMetadata returns response with metadata like status code and response headers
func (c *ApiService) FetchDomainCertV4WithMetadata(DomainSid string) (*metadata.ResourceMetadata[MessagingV2DomainCertV4], error) {
	path := "/v2/LinkShortening/Domains/{DomainSid}/Certificate"
	path = strings.Replace(path, "{"+"DomainSid"+"}", DomainSid, -1)

	data := url.Values{}
	headers := map[string]interface{}{
		"Content-Type": "application/x-www-form-urlencoded",
	}

	resp, err := c.requestHandler.Get(c.baseURL+path, data, headers)
	if err != nil {
		return nil, err
	}

	defer resp.Body.Close()

	ps := &MessagingV2DomainCertV4{}
	if err := json.NewDecoder(resp.Body).Decode(ps); err != nil {
		return nil, err
	}

	metadataWrapper := metadata.NewResourceMetadata[MessagingV2DomainCertV4](
		*ps,             // The resource object
		resp.StatusCode, // HTTP status code
		resp.Header,     // HTTP headers
	)

	return metadataWrapper, nil
}
