/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Messaging
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package openapi

// MessagingV2Request struct for MessagingV2Request
type MessagingV2Request struct {
	// Base64-encoded MD5 hash of the image
	ImageContentMd5 string `json:"imageContentMd5"`
	// MIME type of the image (e.g., image/png, image/jpeg)
	ImageContentType string `json:"imageContentType"`
	// Type of image (logo, hero, etc.)
	ImageKind string `json:"imageKind"`
	// Name of the image file
	ImageName string `json:"imageName"`
	// Size of the image in bytes
	ImageSizeBytes int `json:"imageSizeBytes"`
	// Height of the image in pixels
	ImageHeight int `json:"imageHeight,omitempty"`
	// Width of the image in pixels
	ImageWidth int `json:"imageWidth,omitempty"`
}
